### PR TITLE
External cmake

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
Hmmmm - here my Git fu left me?!

**Comment by rolk** [comment]
It seems to me that you are trying to merge it into the old external-cmake branch, instead of into master.

**Comment by joakim-hove** [comment]
Ok - that might be the case; my caffein level was quite low when I did
this.

J
9. mai 2015 22:15 skrev "Roland Kaufmann" <notifications@github.com>
følgende:

**Comment by joakim-hove** [comment]
Targeting wrong branch - closing.

**Pull request closed without merging**
